// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9tg_QiJy174vc2eRs5DfnZD0-354q6VM',
    appId: '1:53262329474:android:6fad6318c28c76f2e5b69b',
    messagingSenderId: '53262329474',
    projectId: 'jineteapp-3f83c',
    databaseURL: 'https://jineteapp-3f83c-default-rtdb.firebaseio.com',
    storageBucket: 'jineteapp-3f83c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzAEWiJnBcXy494PYHLjb60kx9yYjujAk',
    appId: '1:53262329474:ios:e78731e33701f4a3e5b69b',
    messagingSenderId: '53262329474',
    projectId: 'jineteapp-3f83c',
    databaseURL: 'https://jineteapp-3f83c-default-rtdb.firebaseio.com',
    storageBucket: 'jineteapp-3f83c.firebasestorage.app',
    iosBundleId: 'com.vrbharat.jineteUserApp',
  );

}