// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4gfqeC-D3kGSbNUmHYF8xdSCPPFEzT6I',
    appId: '1:623431021180:android:5dc907701c3d738d444ff9',
    messagingSenderId: '623431021180',
    projectId: 'jinete-user-app',
    databaseURL: 'https://jinete-user-app-default-rtdb.firebaseio.com',
    storageBucket: 'jinete-user-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjq3ZJa1RslNW-hQkB-xeEObkQOUwsXXA',
    appId: '1:623431021180:ios:e1c91e95412d2e61444ff9',
    messagingSenderId: '623431021180',
    projectId: 'jinete-user-app',
    databaseURL: 'https://jinete-user-app-default-rtdb.firebaseio.com',
    storageBucket: 'jinete-user-app.firebasestorage.app',
    iosBundleId: 'com.example.jineteDriverApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7ybuhWmxzun6fxWYWzj7kCAWRlbYTsoI',
    appId: '1:623431021180:web:7558fa9d7754520b444ff9',
    messagingSenderId: '623431021180',
    projectId: 'jinete-user-app',
    authDomain: 'jinete-user-app.firebaseapp.com',
    databaseURL: 'https://jinete-user-app-default-rtdb.firebaseio.com',
    storageBucket: 'jinete-user-app.firebasestorage.app',
    measurementId: 'G-MGTV8YW94N',
  );

}